server:
  port: 18080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auchan-library
      username: auchan-library
      password: auchan
      auto-index-creation: true
